name: Java CI with Maven
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build jar
        run: mvn --batch-mode --update-snapshots clean compile assembly:single
      - name: Test
        run: mvn --batch-mode --update-snapshots verify
      - name: Run jar
        run: java -jar target/assignment.jar sample-graph.csv
      - name: Release
        uses: svenstaro/upload-release-action@v2
        if: github.ref == 'refs/heads/master'
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: target/assignment.jar
            asset_name: assignment.jar
            tag: ${{ github.ref }}
            overwrite: true

