name: Java CI with Maven
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build jar
        run: mvn --batch-mode --update-snapshots clean compile assembly:single
      - name: Save target
        uses: actions/upload-artifact@v2
        with:
            name: target
            path: target
      - name: Save assignment.jar
        uses: actions/upload-artifact@v2
        with:
            name: assignment.jar
            path: target/assignment.jar
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Restore target
        uses: actions/download-artifact@v2
        with:
            name: target
            path: target
      - name: Test
        run: mvn --batch-mode --update-snapshots verify
  run-jar:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Restore artifact
        uses: actions/download-artifact@v2
        with:
            name: assignment.jar
      - name: Run jar
        run: java -jar assignment.jar sample-graph.csv
  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [test, run-jar]
    steps:
      - name: Restore artifact
        uses: actions/download-artifact@v2
        with:
            name: assignment.jar
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: assignment.jar
            asset_name: assignment.jar
            tag: ${{ github.ref }}-snapshot
            overwrite: true


